name: Build and deploy
on:
  push:
    branches:
      - main
env:
  IMAGE_TAG: ghcr.io/Semester-2-Master/pollen-backend
  AZURE_WEBAPP_NAME: pollenproject
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_TAG }}:${{ github.sha }}
            ${{ env.IMAGE_TAG }}:latest
  # deploy:
  #   runs-on: ubuntu-latest
  #   steps:
  #     # Deploy to Azure Web apps
  #     - name: 'Run Azure webapp deploy action using publish profile credentials'
  #       uses: azure/webapps-deploy@v3
  #       with: 
  #         app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
  #         publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }} # Define secret variable in repository settings as per action documentation
  #         package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'
  